ALTER TABLE roomie.location CONVERT TO CHARACTER SET utf8;
ALTER TABLE roomie.comment CONVERT TO CHARACTER SET utf8;
ALTER TABLE roomie.room CONVERT TO CHARACTER SET utf8;
ALTER TABLE roomie.user CONVERT TO CHARACTER SET utf8;
